#######################################################################################
# Book settings
title : Probabilistic Programming with Pyro
author: Soma S Dhavala
logo: 'pp-with-pyro.png'

# Information about where the book exists on the web
description: >-
  Probabilistic Programming with Pyro, a case-based approach  

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/mlsquare/pp-with-pyro
  path_to_book                : "book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex